Develop
sofya-salmanova/Test pull request #2
Opened 2018-09-18 09:38 UTC by sofya-salmanova

2018-09-18 15:25 UTC, papahoolio requested changes

2018-09-18 15:25 UTC, papahoolio commented on Project/Test/main.py
> +
Давай усложним задачу. 
Запуск сервера вынесем в run.py, а сам обработчик запросов расположим в server.py

2018-09-18 15:25 UTC, papahoolio commented on Project/Test/main.py
> +            body = ';'.join(os.listdir(root_directory)).encode()
отличное развитие возможностей!

2018-09-18 15:25 UTC, papahoolio commented on Project/Test/main.py
> +            body = ';'.join(os.listdir(root_directory)).encode()
однако, мы здесь можем ошибиться с указанием базовой директории и в итоге здесь упадем. 
Надо сделать так, чтобы при всех проблемах:
а) сервер отвечал INTERNAL_SERVER_ERROR
б) писал в консоль о проблеме, которая к этому привела

2018-09-18 15:25 UTC, papahoolio commented on Project/Test/main.py
> +                print(sys.exc_info()[0])
мысль правильная, но print это не совсем канонично.
Давай познакомимся с еще одной стандартной и полезной библиотекой https://docs.python.org/3/howto/logging.html

2018-09-18 15:25 UTC, papahoolio commented on Project/Test/main.py
Кто-то забыл про HEAD )

2018-09-18 15:25 UTC, papahoolio commented on Project/WebClient/main.py
> +    if path == '/list':
прям мини-браузер )

2018-09-18 15:25 UTC, papahoolio commented on Project/WebClient/main.py
> +        list = r.text.split(';')
вот так делать нельзя, ты зарезервированное слово в языке переопределяешь

2018-09-18 15:25 UTC, papahoolio commented on Project/WebClient/main.py
> +        print('[0] exit')
Просчет индекса в отдельной переменной при проходе итерируемой структуры не совсем pythonic way


```python

for count, file_name in enumerate(files, 1):
    print(f'[{count}] {file_name}')
```

2018-09-18 15:25 UTC, papahoolio commented on Project/WebClient/main.py
> +    if path == '/list':
единственное, что здесь функция получается умеет и делать http запросы, и обрабатывать пользовательский ввод.

Так делать не надо. Функция умеет очень много, давай попробуем уменьшить ее возможности.

2018-09-20 20:29 UTC, papahoolio requested changes
Мне нравится все, кроме одной вещи )

2018-09-20 20:29 UTC, papahoolio commented on Project/Test/run.py
> +    my_server.root_directory = root_dir
глобальные переменные это не есть хорошо
выставлять глобальные переменные в других модулях - не хорошо, не хорошо

сможешь что-то придумать еще?

2018-09-21 07:41 UTC, papahoolio commented on Project/Test/server.py
> +                body = ';'.join(os.listdir(self.root_directory)).encode()
А здесь у меня будет вопрос. Понимаешь ли почему так работает и какие особенности могут быть?

2018-09-21 08:15 UTC, sofya-salmanova commented on Project/Test/server.py
> +                body = ';'.join(os.listdir(self.root_directory)).encode()
Потому что эта переменная принадлежит классу HttpProcessor. Её значение будет одинаково для всех экземпляров этого класса. Но для этой задачи это подходит же.

2018-09-21 10:24 UTC, papahoolio commented on Project/Test/server.py
> +                body = ';'.join(os.listdir(self.root_directory)).encode()
А значит ее изменение приведет к изменению во всех экземплярах.

Если я захочу поднять несколько серверов на разных портах, обслуживающих разные директории, сделать я этого соответственно не смогу.

2018-09-21 10:31 UTC, sofya-salmanova commented on Project/Test/server.py
> +                body = ';'.join(os.listdir(self.root_directory)).encode()
Присвоила значение переменной всему классу, а получаю его у экземпляра. Пока для конкретного экземпляра не переопределила эту переменную, то получать будет значение у переменной класса. Не очень явно, т.к. здесь мне не нужно переопределять, то сейчас перепишу по-другому

2018-09-21 10:34 UTC, papahoolio commented on Project/Test/server.py
> +                body = ';'.join(os.listdir(self.root_directory)).encode()
Мою проблему с разными директориями для нескольких экземпляров серверов это не решит (

2018-09-21 10:36 UTC, sofya-salmanova commented on Project/Test/server.py
> +                body = ';'.join(os.listdir(self.root_directory)).encode()
Я могу в __init__  объявление тогда сделать?

2018-09-21 11:10 UTC, sofya-salmanova commented on Project/Test/server.py
> +                body = ';'.join(os.listdir(self.root_directory)).encode()
Попробовала так, нормально?

2018-09-21 11:34 UTC, papahoolio requested changes

2018-09-21 11:34 UTC, papahoolio commented on Project/Test/server.py
> +                body = ';'.join(os.listdir(self.root_directory)).encode()
Да.

А через инстанцирования класса сервера и передачу ему параметра обслуживаемой директории сможешь сделать?

2018-09-21 11:40 UTC, sofya-salmanova commented on Project/Test/server.py
> +                body = ';'.join(os.listdir(self.root_directory)).encode()
сделала, даже работает Оо

2018-09-21 12:03 UTC, papahoolio requested changes

2018-09-21 12:03 UTC, papahoolio commented on Project/Test/server.py
> +        self.root_directory = server.root_directory
Это ок

2018-09-21 12:03 UTC, papahoolio commented on Project/Test/run.py
> +    httpd.root_directory = root_dir
Это не ок. Переменная класса имеет обсуждаемый ранее side-effect..

2018-09-21 12:15 UTC, sofya-salmanova commented on Project/Test/run.py
> +    httpd.root_directory = root_dir
А как тогда правильно сделать?

2018-09-21 12:16 UTC, papahoolio commented on Project/Test/run.py
> +    httpd.root_directory = root_dir
а класс сервера создать на основе существующего и использовать его

2018-09-21 12:30 UTC, papahoolio approved these changes

2018-09-21 12:30 UTC, sofya-salmanova commented on Project/Test/run.py
> +    httpd.root_directory = root_dir
Сделала

2018-09-21 12:47 UTC, merged